/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlertNotification,
  AlertNotificationLookup,
  CreateAlertNotificationCommand,
  DeleteAlertNotificationChannelByUID200Response,
  ErrorResponseBody,
  NotificationTestCommand,
  SuccessResponseBody,
  UpdateAlertNotificationCommand,
  UpdateAlertNotificationWithUidCommand,
} from '../models/index';
import {
    AlertNotificationFromJSON,
    AlertNotificationToJSON,
    AlertNotificationLookupFromJSON,
    AlertNotificationLookupToJSON,
    CreateAlertNotificationCommandFromJSON,
    CreateAlertNotificationCommandToJSON,
    DeleteAlertNotificationChannelByUID200ResponseFromJSON,
    DeleteAlertNotificationChannelByUID200ResponseToJSON,
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    NotificationTestCommandFromJSON,
    NotificationTestCommandToJSON,
    SuccessResponseBodyFromJSON,
    SuccessResponseBodyToJSON,
    UpdateAlertNotificationCommandFromJSON,
    UpdateAlertNotificationCommandToJSON,
    UpdateAlertNotificationWithUidCommandFromJSON,
    UpdateAlertNotificationWithUidCommandToJSON,
} from '../models/index';

export interface LegacyAlertsNotificationChannelsApiCreateAlertNotificationChannelRequest {
    body: CreateAlertNotificationCommand;
}

export interface LegacyAlertsNotificationChannelsApiDeleteAlertNotificationChannelRequest {
    notificationChannelId: number;
}

export interface LegacyAlertsNotificationChannelsApiDeleteAlertNotificationChannelByUIDRequest {
    notificationChannelUid: string;
}

export interface LegacyAlertsNotificationChannelsApiGetAlertNotificationChannelByIDRequest {
    notificationChannelId: number;
}

export interface LegacyAlertsNotificationChannelsApiGetAlertNotificationChannelByUIDRequest {
    notificationChannelUid: string;
}

export interface LegacyAlertsNotificationChannelsApiNotificationChannelTestRequest {
    body: NotificationTestCommand;
}

export interface LegacyAlertsNotificationChannelsApiUpdateAlertNotificationChannelRequest {
    notificationChannelId: number;
    body: UpdateAlertNotificationCommand;
}

export interface LegacyAlertsNotificationChannelsApiUpdateAlertNotificationChannelByUIDRequest {
    notificationChannelUid: string;
    body: UpdateAlertNotificationWithUidCommand;
}

/**
 * 
 */
export class LegacyAlertsNotificationChannelsApi extends runtime.BaseAPI {

    /**
     * You can find the full list of [supported notifiers](https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/#list-of-supported-notifiers) on the alert notifiers page.
     * Create notification channel.
     */
    async createAlertNotificationChannelRaw(requestParameters: LegacyAlertsNotificationChannelsApiCreateAlertNotificationChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertNotification>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createAlertNotificationChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAlertNotificationCommandToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlertNotificationFromJSON(jsonValue));
    }

    /**
     * You can find the full list of [supported notifiers](https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/#list-of-supported-notifiers) on the alert notifiers page.
     * Create notification channel.
     */
    async createAlertNotificationChannel(requestParameters: LegacyAlertsNotificationChannelsApiCreateAlertNotificationChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertNotification> {
        const response = await this.createAlertNotificationChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing notification channel identified by ID.
     * Delete alert notification by ID.
     */
    async deleteAlertNotificationChannelRaw(requestParameters: LegacyAlertsNotificationChannelsApiDeleteAlertNotificationChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseBody>> {
        if (requestParameters['notificationChannelId'] == null) {
            throw new runtime.RequiredError(
                'notificationChannelId',
                'Required parameter "notificationChannelId" was null or undefined when calling deleteAlertNotificationChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/{notification_channel_id}`.replace(`{${"notification_channel_id"}}`, encodeURIComponent(String(requestParameters['notificationChannelId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseBodyFromJSON(jsonValue));
    }

    /**
     * Deletes an existing notification channel identified by ID.
     * Delete alert notification by ID.
     */
    async deleteAlertNotificationChannel(requestParameters: LegacyAlertsNotificationChannelsApiDeleteAlertNotificationChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseBody> {
        const response = await this.deleteAlertNotificationChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an existing notification channel identified by UID.
     * Delete alert notification by UID.
     */
    async deleteAlertNotificationChannelByUIDRaw(requestParameters: LegacyAlertsNotificationChannelsApiDeleteAlertNotificationChannelByUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAlertNotificationChannelByUID200Response>> {
        if (requestParameters['notificationChannelUid'] == null) {
            throw new runtime.RequiredError(
                'notificationChannelUid',
                'Required parameter "notificationChannelUid" was null or undefined when calling deleteAlertNotificationChannelByUID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/uid/{notification_channel_uid}`.replace(`{${"notification_channel_uid"}}`, encodeURIComponent(String(requestParameters['notificationChannelUid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAlertNotificationChannelByUID200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes an existing notification channel identified by UID.
     * Delete alert notification by UID.
     */
    async deleteAlertNotificationChannelByUID(requestParameters: LegacyAlertsNotificationChannelsApiDeleteAlertNotificationChannelByUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAlertNotificationChannelByUID200Response> {
        const response = await this.deleteAlertNotificationChannelByUIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the notification channel given the notification channel ID.
     * Get notification channel by ID.
     */
    async getAlertNotificationChannelByIDRaw(requestParameters: LegacyAlertsNotificationChannelsApiGetAlertNotificationChannelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertNotification>> {
        if (requestParameters['notificationChannelId'] == null) {
            throw new runtime.RequiredError(
                'notificationChannelId',
                'Required parameter "notificationChannelId" was null or undefined when calling getAlertNotificationChannelByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/{notification_channel_id}`.replace(`{${"notification_channel_id"}}`, encodeURIComponent(String(requestParameters['notificationChannelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlertNotificationFromJSON(jsonValue));
    }

    /**
     * Returns the notification channel given the notification channel ID.
     * Get notification channel by ID.
     */
    async getAlertNotificationChannelByID(requestParameters: LegacyAlertsNotificationChannelsApiGetAlertNotificationChannelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertNotification> {
        const response = await this.getAlertNotificationChannelByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the notification channel given the notification channel UID.
     * Get notification channel by UID.
     */
    async getAlertNotificationChannelByUIDRaw(requestParameters: LegacyAlertsNotificationChannelsApiGetAlertNotificationChannelByUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertNotification>> {
        if (requestParameters['notificationChannelUid'] == null) {
            throw new runtime.RequiredError(
                'notificationChannelUid',
                'Required parameter "notificationChannelUid" was null or undefined when calling getAlertNotificationChannelByUID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/uid/{notification_channel_uid}`.replace(`{${"notification_channel_uid"}}`, encodeURIComponent(String(requestParameters['notificationChannelUid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlertNotificationFromJSON(jsonValue));
    }

    /**
     * Returns the notification channel given the notification channel UID.
     * Get notification channel by UID.
     */
    async getAlertNotificationChannelByUID(requestParameters: LegacyAlertsNotificationChannelsApiGetAlertNotificationChannelByUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertNotification> {
        const response = await this.getAlertNotificationChannelByUIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all notification channels that the authenticated user has permission to view.
     * Get all notification channels.
     */
    async getAlertNotificationChannelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlertNotification>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlertNotificationFromJSON));
    }

    /**
     * Returns all notification channels that the authenticated user has permission to view.
     * Get all notification channels.
     */
    async getAlertNotificationChannels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlertNotification>> {
        const response = await this.getAlertNotificationChannelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all notification channels, but with less detailed information. Accessible by any authenticated user and is mainly used by providing alert notification channels in Grafana UI when configuring alert rule.
     * Get all notification channels (lookup).
     */
    async getAlertNotificationLookupRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlertNotificationLookup>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/lookup`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlertNotificationLookupFromJSON));
    }

    /**
     * Returns all notification channels, but with less detailed information. Accessible by any authenticated user and is mainly used by providing alert notification channels in Grafana UI when configuring alert rule.
     * Get all notification channels (lookup).
     */
    async getAlertNotificationLookup(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlertNotificationLookup>> {
        const response = await this.getAlertNotificationLookupRaw(initOverrides);
        return await response.value();
    }

    /**
     * Sends a test notification to the channel.
     * Test notification channel.
     */
    async notificationChannelTestRaw(requestParameters: LegacyAlertsNotificationChannelsApiNotificationChannelTestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseBody>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling notificationChannelTest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/test`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationTestCommandToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseBodyFromJSON(jsonValue));
    }

    /**
     * Sends a test notification to the channel.
     * Test notification channel.
     */
    async notificationChannelTest(requestParameters: LegacyAlertsNotificationChannelsApiNotificationChannelTestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseBody> {
        const response = await this.notificationChannelTestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing notification channel identified by ID.
     * Update notification channel by ID.
     */
    async updateAlertNotificationChannelRaw(requestParameters: LegacyAlertsNotificationChannelsApiUpdateAlertNotificationChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertNotification>> {
        if (requestParameters['notificationChannelId'] == null) {
            throw new runtime.RequiredError(
                'notificationChannelId',
                'Required parameter "notificationChannelId" was null or undefined when calling updateAlertNotificationChannel().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateAlertNotificationChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/{notification_channel_id}`.replace(`{${"notification_channel_id"}}`, encodeURIComponent(String(requestParameters['notificationChannelId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAlertNotificationCommandToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlertNotificationFromJSON(jsonValue));
    }

    /**
     * Updates an existing notification channel identified by ID.
     * Update notification channel by ID.
     */
    async updateAlertNotificationChannel(requestParameters: LegacyAlertsNotificationChannelsApiUpdateAlertNotificationChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertNotification> {
        const response = await this.updateAlertNotificationChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing notification channel identified by uid.
     * Update notification channel by UID.
     */
    async updateAlertNotificationChannelByUIDRaw(requestParameters: LegacyAlertsNotificationChannelsApiUpdateAlertNotificationChannelByUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertNotification>> {
        if (requestParameters['notificationChannelUid'] == null) {
            throw new runtime.RequiredError(
                'notificationChannelUid',
                'Required parameter "notificationChannelUid" was null or undefined when calling updateAlertNotificationChannelByUID().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateAlertNotificationChannelByUID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/alert-notifications/uid/{notification_channel_uid}`.replace(`{${"notification_channel_uid"}}`, encodeURIComponent(String(requestParameters['notificationChannelUid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAlertNotificationWithUidCommandToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlertNotificationFromJSON(jsonValue));
    }

    /**
     * Updates an existing notification channel identified by uid.
     * Update notification channel by UID.
     */
    async updateAlertNotificationChannelByUID(requestParameters: LegacyAlertsNotificationChannelsApiUpdateAlertNotificationChannelByUIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertNotification> {
        const response = await this.updateAlertNotificationChannelByUIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
