/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AddInviteForm,
  ErrorResponseBody,
  SuccessResponseBody,
  TempUserDTO,
} from '../models/index.js';
import {
    AddInviteFormFromJSON,
    AddInviteFormToJSON,
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    SuccessResponseBodyFromJSON,
    SuccessResponseBodyToJSON,
    TempUserDTOFromJSON,
    TempUserDTOToJSON,
} from '../models/index.js';

export interface OrgInvitesApiAddOrgInviteRequest {
    body: AddInviteForm;
}

export interface OrgInvitesApiRevokeInviteRequest {
    invitationCode: string;
}

/**
 * 
 */
export class OrgInvitesApi extends runtime.BaseAPI {

    /**
     * Add invite.
     */
    async addOrgInviteRaw(requestParameters: OrgInvitesApiAddOrgInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseBody>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling addOrgInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/org/invites`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddInviteFormToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseBodyFromJSON(jsonValue));
    }

    /**
     * Add invite.
     */
    async addOrgInvite(requestParameters: OrgInvitesApiAddOrgInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseBody> {
        const response = await this.addOrgInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get pending invites.
     */
    async getPendingOrgInvitesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TempUserDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/org/invites`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TempUserDTOFromJSON));
    }

    /**
     * Get pending invites.
     */
    async getPendingOrgInvites(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TempUserDTO>> {
        const response = await this.getPendingOrgInvitesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Revoke invite.
     */
    async revokeInviteRaw(requestParameters: OrgInvitesApiRevokeInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponseBody>> {
        if (requestParameters['invitationCode'] == null) {
            throw new runtime.RequiredError(
                'invitationCode',
                'Required parameter "invitationCode" was null or undefined when calling revokeInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // api_key authentication
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/org/invites/{invitation_code}/revoke`.replace(`{${"invitation_code"}}`, encodeURIComponent(String(requestParameters['invitationCode']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseBodyFromJSON(jsonValue));
    }

    /**
     * Revoke invite.
     */
    async revokeInvite(requestParameters: OrgInvitesApiRevokeInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponseBody> {
        const response = await this.revokeInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
