/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTeamMemberCommand
 */
export interface AddTeamMemberCommand {
    /**
     * 
     * @type {number}
     * @memberof AddTeamMemberCommand
     */
    userId?: number;
}

/**
 * Check if a given object implements the AddTeamMemberCommand interface.
 */
export function instanceOfAddTeamMemberCommand(value: object): value is AddTeamMemberCommand {
    return true;
}

export function AddTeamMemberCommandFromJSON(json: any): AddTeamMemberCommand {
    return AddTeamMemberCommandFromJSONTyped(json, false);
}

export function AddTeamMemberCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTeamMemberCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function AddTeamMemberCommandToJSON(json: any): AddTeamMemberCommand {
    return AddTeamMemberCommandToJSONTyped(json, false);
}

export function AddTeamMemberCommandToJSONTyped(value?: AddTeamMemberCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

