/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VersionInfo } from './VersionInfo.js';
import {
    VersionInfoFromJSON,
    VersionInfoFromJSONTyped,
    VersionInfoToJSON,
    VersionInfoToJSONTyped,
} from './VersionInfo.js';
import type { AlertmanagerConfig } from './AlertmanagerConfig.js';
import {
    AlertmanagerConfigFromJSON,
    AlertmanagerConfigFromJSONTyped,
    AlertmanagerConfigToJSON,
    AlertmanagerConfigToJSONTyped,
} from './AlertmanagerConfig.js';
import type { ClusterStatus } from './ClusterStatus.js';
import {
    ClusterStatusFromJSON,
    ClusterStatusFromJSONTyped,
    ClusterStatusToJSON,
    ClusterStatusToJSONTyped,
} from './ClusterStatus.js';

/**
 * AlertmanagerStatus alertmanager status
 * @export
 * @interface AlertmanagerStatus
 */
export interface AlertmanagerStatus {
    /**
     * 
     * @type {ClusterStatus}
     * @memberof AlertmanagerStatus
     */
    cluster: ClusterStatus;
    /**
     * 
     * @type {AlertmanagerConfig}
     * @memberof AlertmanagerStatus
     */
    config: AlertmanagerConfig;
    /**
     * uptime
     * @type {Date}
     * @memberof AlertmanagerStatus
     */
    uptime: Date;
    /**
     * 
     * @type {VersionInfo}
     * @memberof AlertmanagerStatus
     */
    versionInfo: VersionInfo;
}

/**
 * Check if a given object implements the AlertmanagerStatus interface.
 */
export function instanceOfAlertmanagerStatus(value: object): value is AlertmanagerStatus {
    if (!('cluster' in value) || value['cluster'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('uptime' in value) || value['uptime'] === undefined) return false;
    if (!('versionInfo' in value) || value['versionInfo'] === undefined) return false;
    return true;
}

export function AlertmanagerStatusFromJSON(json: any): AlertmanagerStatus {
    return AlertmanagerStatusFromJSONTyped(json, false);
}

export function AlertmanagerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertmanagerStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'cluster': ClusterStatusFromJSON(json['cluster']),
        'config': AlertmanagerConfigFromJSON(json['config']),
        'uptime': (new Date(json['uptime'])),
        'versionInfo': VersionInfoFromJSON(json['versionInfo']),
    };
}

export function AlertmanagerStatusToJSON(json: any): AlertmanagerStatus {
    return AlertmanagerStatusToJSONTyped(json, false);
}

export function AlertmanagerStatusToJSONTyped(value?: AlertmanagerStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cluster': ClusterStatusToJSON(value['cluster']),
        'config': AlertmanagerConfigToJSON(value['config']),
        'uptime': ((value['uptime']).toISOString()),
        'versionInfo': VersionInfoToJSON(value['versionInfo']),
    };
}

