/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AlertDiscovery } from './AlertDiscovery.js';
import {
    AlertDiscoveryFromJSON,
    AlertDiscoveryFromJSONTyped,
    AlertDiscoveryToJSON,
    AlertDiscoveryToJSONTyped,
} from './AlertDiscovery.js';

/**
 * 
 * @export
 * @interface AlertResponse
 */
export interface AlertResponse {
    /**
     * 
     * @type {AlertDiscovery}
     * @memberof AlertResponse
     */
    data?: AlertDiscovery;
    /**
     * 
     * @type {string}
     * @memberof AlertResponse
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof AlertResponse
     */
    errorType?: string;
    /**
     * 
     * @type {string}
     * @memberof AlertResponse
     */
    status: string;
}

/**
 * Check if a given object implements the AlertResponse interface.
 */
export function instanceOfAlertResponse(value: object): value is AlertResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AlertResponseFromJSON(json: any): AlertResponse {
    return AlertResponseFromJSONTyped(json, false);
}

export function AlertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AlertDiscoveryFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'errorType': json['errorType'] == null ? undefined : json['errorType'],
        'status': json['status'],
    };
}

export function AlertResponseToJSON(json: any): AlertResponse {
    return AlertResponseToJSONTyped(json, false);
}

export function AlertResponseToJSONTyped(value?: AlertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AlertDiscoveryToJSON(value['data']),
        'error': value['error'],
        'errorType': value['errorType'],
        'status': value['status'],
    };
}

