/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertNotificationLookup
 */
export interface AlertNotificationLookup {
    /**
     * 
     * @type {number}
     * @memberof AlertNotificationLookup
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AlertNotificationLookup
     */
    isDefault?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlertNotificationLookup
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AlertNotificationLookup
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof AlertNotificationLookup
     */
    uid?: string;
}

/**
 * Check if a given object implements the AlertNotificationLookup interface.
 */
export function instanceOfAlertNotificationLookup(value: object): value is AlertNotificationLookup {
    return true;
}

export function AlertNotificationLookupFromJSON(json: any): AlertNotificationLookup {
    return AlertNotificationLookupFromJSONTyped(json, false);
}

export function AlertNotificationLookupFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertNotificationLookup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function AlertNotificationLookupToJSON(json: any): AlertNotificationLookup {
    return AlertNotificationLookupToJSONTyped(json, false);
}

export function AlertNotificationLookupToJSONTyped(value?: AlertNotificationLookup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'isDefault': value['isDefault'],
        'name': value['name'],
        'type': value['type'],
        'uid': value['uid'],
    };
}

