/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertNotification
 */
export interface AlertNotification {
    /**
     * 
     * @type {Date}
     * @memberof AlertNotification
     */
    created?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AlertNotification
     */
    disableResolveMessage?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlertNotification
     */
    frequency?: string;
    /**
     * 
     * @type {number}
     * @memberof AlertNotification
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AlertNotification
     */
    isDefault?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlertNotification
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof AlertNotification
     */
    secureFields?: { [key: string]: boolean; };
    /**
     * 
     * @type {boolean}
     * @memberof AlertNotification
     */
    sendReminder?: boolean;
    /**
     * 
     * @type {object}
     * @memberof AlertNotification
     */
    settings?: object;
    /**
     * 
     * @type {string}
     * @memberof AlertNotification
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof AlertNotification
     */
    uid?: string;
    /**
     * 
     * @type {Date}
     * @memberof AlertNotification
     */
    updated?: Date;
}

/**
 * Check if a given object implements the AlertNotification interface.
 */
export function instanceOfAlertNotification(value: object): value is AlertNotification {
    return true;
}

export function AlertNotificationFromJSON(json: any): AlertNotification {
    return AlertNotificationFromJSONTyped(json, false);
}

export function AlertNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'disableResolveMessage': json['disableResolveMessage'] == null ? undefined : json['disableResolveMessage'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'id': json['id'] == null ? undefined : json['id'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'name': json['name'] == null ? undefined : json['name'],
        'secureFields': json['secureFields'] == null ? undefined : json['secureFields'],
        'sendReminder': json['sendReminder'] == null ? undefined : json['sendReminder'],
        'settings': json['settings'] == null ? undefined : json['settings'],
        'type': json['type'] == null ? undefined : json['type'],
        'uid': json['uid'] == null ? undefined : json['uid'],
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
    };
}

export function AlertNotificationToJSON(json: any): AlertNotification {
    return AlertNotificationToJSONTyped(json, false);
}

export function AlertNotificationToJSONTyped(value?: AlertNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'disableResolveMessage': value['disableResolveMessage'],
        'frequency': value['frequency'],
        'id': value['id'],
        'isDefault': value['isDefault'],
        'name': value['name'],
        'secureFields': value['secureFields'],
        'sendReminder': value['sendReminder'],
        'settings': value['settings'],
        'type': value['type'],
        'uid': value['uid'],
        'updated': value['updated'] == null ? undefined : ((value['updated']).toISOString()),
    };
}

