/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CalculateDiffTarget
 */
export interface CalculateDiffTarget {
    /**
     * 
     * @type {number}
     * @memberof CalculateDiffTarget
     */
    dashboardId?: number;
    /**
     * 
     * @type {object}
     * @memberof CalculateDiffTarget
     */
    unsavedDashboard?: object;
    /**
     * 
     * @type {number}
     * @memberof CalculateDiffTarget
     */
    version?: number;
}

/**
 * Check if a given object implements the CalculateDiffTarget interface.
 */
export function instanceOfCalculateDiffTarget(value: object): value is CalculateDiffTarget {
    return true;
}

export function CalculateDiffTargetFromJSON(json: any): CalculateDiffTarget {
    return CalculateDiffTargetFromJSONTyped(json, false);
}

export function CalculateDiffTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalculateDiffTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboardId': json['dashboardId'] == null ? undefined : json['dashboardId'],
        'unsavedDashboard': json['unsavedDashboard'] == null ? undefined : json['unsavedDashboard'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function CalculateDiffTargetToJSON(json: any): CalculateDiffTarget {
    return CalculateDiffTargetToJSONTyped(json, false);
}

export function CalculateDiffTargetToJSONTyped(value?: CalculateDiffTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dashboardId': value['dashboardId'],
        'unsavedDashboard': value['unsavedDashboard'],
        'version': value['version'],
    };
}

