/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CloudMigrationSessionRequestDTO
 */
export interface CloudMigrationSessionRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof CloudMigrationSessionRequestDTO
     */
    authToken?: string;
}

/**
 * Check if a given object implements the CloudMigrationSessionRequestDTO interface.
 */
export function instanceOfCloudMigrationSessionRequestDTO(value: object): value is CloudMigrationSessionRequestDTO {
    return true;
}

export function CloudMigrationSessionRequestDTOFromJSON(json: any): CloudMigrationSessionRequestDTO {
    return CloudMigrationSessionRequestDTOFromJSONTyped(json, false);
}

export function CloudMigrationSessionRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudMigrationSessionRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'authToken': json['authToken'] == null ? undefined : json['authToken'],
    };
}

export function CloudMigrationSessionRequestDTOToJSON(json: any): CloudMigrationSessionRequestDTO {
    return CloudMigrationSessionRequestDTOToJSONTyped(json, false);
}

export function CloudMigrationSessionRequestDTOToJSONTyped(value?: CloudMigrationSessionRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authToken': value['authToken'],
    };
}

