/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MigrateDataResponseListDTO } from './MigrateDataResponseListDTO';
import {
    MigrateDataResponseListDTOFromJSON,
    MigrateDataResponseListDTOFromJSONTyped,
    MigrateDataResponseListDTOToJSON,
    MigrateDataResponseListDTOToJSONTyped,
} from './MigrateDataResponseListDTO';

/**
 * 
 * @export
 * @interface CloudMigrationRunListDTO
 */
export interface CloudMigrationRunListDTO {
    /**
     * 
     * @type {Array<MigrateDataResponseListDTO>}
     * @memberof CloudMigrationRunListDTO
     */
    runs?: Array<MigrateDataResponseListDTO>;
}

/**
 * Check if a given object implements the CloudMigrationRunListDTO interface.
 */
export function instanceOfCloudMigrationRunListDTO(value: object): value is CloudMigrationRunListDTO {
    return true;
}

export function CloudMigrationRunListDTOFromJSON(json: any): CloudMigrationRunListDTO {
    return CloudMigrationRunListDTOFromJSONTyped(json, false);
}

export function CloudMigrationRunListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudMigrationRunListDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'runs': json['runs'] == null ? undefined : ((json['runs'] as Array<any>).map(MigrateDataResponseListDTOFromJSON)),
    };
}

export function CloudMigrationRunListDTOToJSON(json: any): CloudMigrationRunListDTO {
    return CloudMigrationRunListDTOToJSONTyped(json, false);
}

export function CloudMigrationRunListDTOToJSONTyped(value?: CloudMigrationRunListDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'runs': value['runs'] == null ? undefined : ((value['runs'] as Array<any>).map(MigrateDataResponseListDTOToJSON)),
    };
}

