/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Matcher } from './Matcher';
import {
    MatcherFromJSON,
    MatcherFromJSONTyped,
    MatcherToJSON,
    MatcherToJSONTyped,
} from './Matcher';

/**
 * 
 * @export
 * @interface ContactPointUpgrade
 */
export interface ContactPointUpgrade {
    /**
     * 
     * @type {string}
     * @memberof ContactPointUpgrade
     */
    name?: string;
    /**
     * Matchers is a slice of Matchers that is sortable, implements Stringer, and
     * provides a Matches method to match a LabelSet against all Matchers in the
     * slice. Note that some users of Matchers might require it to be sorted.
     * @type {Array<Matcher>}
     * @memberof ContactPointUpgrade
     */
    routeMatchers?: Array<Matcher>;
    /**
     * 
     * @type {string}
     * @memberof ContactPointUpgrade
     */
    type?: string;
}

/**
 * Check if a given object implements the ContactPointUpgrade interface.
 */
export function instanceOfContactPointUpgrade(value: object): value is ContactPointUpgrade {
    return true;
}

export function ContactPointUpgradeFromJSON(json: any): ContactPointUpgrade {
    return ContactPointUpgradeFromJSONTyped(json, false);
}

export function ContactPointUpgradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactPointUpgrade {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'routeMatchers': json['routeMatchers'] == null ? undefined : ((json['routeMatchers'] as Array<any>).map(MatcherFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ContactPointUpgradeToJSON(json: any): ContactPointUpgrade {
    return ContactPointUpgradeToJSONTyped(json, false);
}

export function ContactPointUpgradeToJSONTyped(value?: ContactPointUpgrade | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'routeMatchers': value['routeMatchers'] == null ? undefined : ((value['routeMatchers'] as Array<any>).map(MatcherToJSON)),
        'type': value['type'],
    };
}

