/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DashboardReportDTO } from './DashboardReportDTO';
import {
    DashboardReportDTOFromJSON,
    DashboardReportDTOFromJSONTyped,
    DashboardReportDTOToJSON,
    DashboardReportDTOToJSONTyped,
} from './DashboardReportDTO';
import type { TimeRangeDTO } from './TimeRangeDTO';
import {
    TimeRangeDTOFromJSON,
    TimeRangeDTOFromJSONTyped,
    TimeRangeDTOToJSON,
    TimeRangeDTOToJSONTyped,
} from './TimeRangeDTO';

/**
 * 
 * @export
 * @interface DashboardDTO
 */
export interface DashboardDTO {
    /**
     * 
     * @type {DashboardReportDTO}
     * @memberof DashboardDTO
     */
    dashboard?: DashboardReportDTO;
    /**
     * 
     * @type {object}
     * @memberof DashboardDTO
     */
    reportVariables?: object;
    /**
     * 
     * @type {TimeRangeDTO}
     * @memberof DashboardDTO
     */
    timeRange?: TimeRangeDTO;
}

/**
 * Check if a given object implements the DashboardDTO interface.
 */
export function instanceOfDashboardDTO(value: object): value is DashboardDTO {
    return true;
}

export function DashboardDTOFromJSON(json: any): DashboardDTO {
    return DashboardDTOFromJSONTyped(json, false);
}

export function DashboardDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboard': json['dashboard'] == null ? undefined : DashboardReportDTOFromJSON(json['dashboard']),
        'reportVariables': json['reportVariables'] == null ? undefined : json['reportVariables'],
        'timeRange': json['timeRange'] == null ? undefined : TimeRangeDTOFromJSON(json['timeRange']),
    };
}

export function DashboardDTOToJSON(json: any): DashboardDTO {
    return DashboardDTOToJSONTyped(json, false);
}

export function DashboardDTOToJSONTyped(value?: DashboardDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dashboard': DashboardReportDTOToJSON(value['dashboard']),
        'reportVariables': value['reportVariables'],
        'timeRange': TimeRangeDTOToJSON(value['timeRange']),
    };
}

