/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteDashboardByUID200Response
 */
export interface DeleteDashboardByUID200Response {
    /**
     * ID Identifier of the deleted dashboard.
     * @type {number}
     * @memberof DeleteDashboardByUID200Response
     */
    id: number;
    /**
     * Message Message of the deleted dashboard.
     * @type {string}
     * @memberof DeleteDashboardByUID200Response
     */
    message: string;
    /**
     * Title Title of the deleted dashboard.
     * @type {string}
     * @memberof DeleteDashboardByUID200Response
     */
    title: string;
}

/**
 * Check if a given object implements the DeleteDashboardByUID200Response interface.
 */
export function instanceOfDeleteDashboardByUID200Response(value: object): value is DeleteDashboardByUID200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function DeleteDashboardByUID200ResponseFromJSON(json: any): DeleteDashboardByUID200Response {
    return DeleteDashboardByUID200ResponseFromJSONTyped(json, false);
}

export function DeleteDashboardByUID200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteDashboardByUID200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
        'title': json['title'],
    };
}

export function DeleteDashboardByUID200ResponseToJSON(json: any): DeleteDashboardByUID200Response {
    return DeleteDashboardByUID200ResponseToJSONTyped(json, false);
}

export function DeleteDashboardByUID200ResponseToJSONTyped(value?: DeleteDashboardByUID200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
        'title': value['title'],
    };
}

