/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Assignments } from './Assignments.js';
import {
    AssignmentsFromJSON,
    AssignmentsFromJSONTyped,
    AssignmentsToJSON,
    AssignmentsToJSONTyped,
} from './Assignments.js';

/**
 * 
 * @export
 * @interface Description
 */
export interface Description {
    /**
     * 
     * @type {Assignments}
     * @memberof Description
     */
    assignments?: Assignments;
    /**
     * 
     * @type {Array<string>}
     * @memberof Description
     */
    permissions?: Array<string>;
}

/**
 * Check if a given object implements the Description interface.
 */
export function instanceOfDescription(value: object): value is Description {
    return true;
}

export function DescriptionFromJSON(json: any): Description {
    return DescriptionFromJSONTyped(json, false);
}

export function DescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Description {
    if (json == null) {
        return json;
    }
    return {
        
        'assignments': json['assignments'] == null ? undefined : AssignmentsFromJSON(json['assignments']),
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function DescriptionToJSON(json: any): Description {
    return DescriptionToJSONTyped(json, false);
}

export function DescriptionToJSONTyped(value?: Description | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignments': AssignmentsToJSON(value['assignments']),
        'permissions': value['permissions'],
    };
}

