/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LibraryElementDTOMetaUser
 */
export interface LibraryElementDTOMetaUser {
    /**
     * 
     * @type {string}
     * @memberof LibraryElementDTOMetaUser
     */
    avatarUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof LibraryElementDTOMetaUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LibraryElementDTOMetaUser
     */
    name?: string;
}

/**
 * Check if a given object implements the LibraryElementDTOMetaUser interface.
 */
export function instanceOfLibraryElementDTOMetaUser(value: object): value is LibraryElementDTOMetaUser {
    return true;
}

export function LibraryElementDTOMetaUserFromJSON(json: any): LibraryElementDTOMetaUser {
    return LibraryElementDTOMetaUserFromJSONTyped(json, false);
}

export function LibraryElementDTOMetaUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibraryElementDTOMetaUser {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function LibraryElementDTOMetaUserToJSON(json: any): LibraryElementDTOMetaUser {
    return LibraryElementDTOMetaUserToJSONTyped(json, false);
}

export function LibraryElementDTOMetaUserToJSONTyped(value?: LibraryElementDTOMetaUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatarUrl': value['avatarUrl'],
        'id': value['id'],
        'name': value['name'],
    };
}

