/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FloatHistogram } from './FloatHistogram';
import {
    FloatHistogramFromJSON,
    FloatHistogramFromJSONTyped,
    FloatHistogramToJSON,
    FloatHistogramToJSONTyped,
} from './FloatHistogram';

/**
 * If H is not nil, then this is a histogram point and only (T, H) is valid.
 * If H is nil, then only (T, V) is valid.
 * @export
 * @interface Point
 */
export interface Point {
    /**
     * 
     * @type {FloatHistogram}
     * @memberof Point
     */
    h?: FloatHistogram;
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    t?: number;
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    v?: number;
}

/**
 * Check if a given object implements the Point interface.
 */
export function instanceOfPoint(value: object): value is Point {
    return true;
}

export function PointFromJSON(json: any): Point {
    return PointFromJSONTyped(json, false);
}

export function PointFromJSONTyped(json: any, ignoreDiscriminator: boolean): Point {
    if (json == null) {
        return json;
    }
    return {
        
        'h': json['H'] == null ? undefined : FloatHistogramFromJSON(json['H']),
        't': json['T'] == null ? undefined : json['T'],
        'v': json['V'] == null ? undefined : json['V'],
    };
}

export function PointToJSON(json: any): Point {
    return PointToJSONTyped(json, false);
}

export function PointToJSONTyped(value?: Point | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'H': FloatHistogramToJSON(value['h']),
        'T': value['t'],
        'V': value['v'],
    };
}

