/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSilencesOKBody
 */
export interface PostSilencesOKBody {
    /**
     * silence ID
     * @type {string}
     * @memberof PostSilencesOKBody
     */
    silenceID?: string;
}

/**
 * Check if a given object implements the PostSilencesOKBody interface.
 */
export function instanceOfPostSilencesOKBody(value: object): value is PostSilencesOKBody {
    return true;
}

export function PostSilencesOKBodyFromJSON(json: any): PostSilencesOKBody {
    return PostSilencesOKBodyFromJSONTyped(json, false);
}

export function PostSilencesOKBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSilencesOKBody {
    if (json == null) {
        return json;
    }
    return {
        
        'silenceID': json['silenceID'] == null ? undefined : json['silenceID'],
    };
}

export function PostSilencesOKBodyToJSON(json: any): PostSilencesOKBody {
    return PostSilencesOKBodyToJSONTyped(json, false);
}

export function PostSilencesOKBodyToJSONTyped(value?: PostSilencesOKBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'silenceID': value['silenceID'],
    };
}

