/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NavbarPreference } from './NavbarPreference.js';
import {
    NavbarPreferenceFromJSON,
    NavbarPreferenceFromJSONTyped,
    NavbarPreferenceToJSON,
    NavbarPreferenceToJSONTyped,
} from './NavbarPreference.js';
import type { QueryHistoryPreference } from './QueryHistoryPreference.js';
import {
    QueryHistoryPreferenceFromJSON,
    QueryHistoryPreferenceFromJSONTyped,
    QueryHistoryPreferenceToJSON,
    QueryHistoryPreferenceToJSONTyped,
} from './QueryHistoryPreference.js';
import type { CookiePreferences } from './CookiePreferences.js';
import {
    CookiePreferencesFromJSON,
    CookiePreferencesFromJSONTyped,
    CookiePreferencesToJSON,
    CookiePreferencesToJSONTyped,
} from './CookiePreferences.js';

/**
 * Spec defines user, team or org Grafana preferences
 * @export
 * @interface Preferences
 */
export interface Preferences {
    /**
     * 
     * @type {CookiePreferences}
     * @memberof Preferences
     */
    cookiePreferences?: CookiePreferences;
    /**
     * UID for the home dashboard
     * @type {string}
     * @memberof Preferences
     */
    homeDashboardUID?: string;
    /**
     * Selected language (beta)
     * @type {string}
     * @memberof Preferences
     */
    language?: string;
    /**
     * 
     * @type {NavbarPreference}
     * @memberof Preferences
     */
    navbar?: NavbarPreference;
    /**
     * 
     * @type {QueryHistoryPreference}
     * @memberof Preferences
     */
    queryHistory?: QueryHistoryPreference;
    /**
     * Theme light, dark, empty is default
     * @type {string}
     * @memberof Preferences
     */
    theme?: string;
    /**
     * The timezone selection
     * TODO: this should use the timezone defined in common
     * @type {string}
     * @memberof Preferences
     */
    timezone?: string;
    /**
     * WeekStart day of the week (sunday, monday, etc)
     * @type {string}
     * @memberof Preferences
     */
    weekStart?: string;
}

/**
 * Check if a given object implements the Preferences interface.
 */
export function instanceOfPreferences(value: object): value is Preferences {
    return true;
}

export function PreferencesFromJSON(json: any): Preferences {
    return PreferencesFromJSONTyped(json, false);
}

export function PreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preferences {
    if (json == null) {
        return json;
    }
    return {
        
        'cookiePreferences': json['cookiePreferences'] == null ? undefined : CookiePreferencesFromJSON(json['cookiePreferences']),
        'homeDashboardUID': json['homeDashboardUID'] == null ? undefined : json['homeDashboardUID'],
        'language': json['language'] == null ? undefined : json['language'],
        'navbar': json['navbar'] == null ? undefined : NavbarPreferenceFromJSON(json['navbar']),
        'queryHistory': json['queryHistory'] == null ? undefined : QueryHistoryPreferenceFromJSON(json['queryHistory']),
        'theme': json['theme'] == null ? undefined : json['theme'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'weekStart': json['weekStart'] == null ? undefined : json['weekStart'],
    };
}

export function PreferencesToJSON(json: any): Preferences {
    return PreferencesToJSONTyped(json, false);
}

export function PreferencesToJSONTyped(value?: Preferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cookiePreferences': CookiePreferencesToJSON(value['cookiePreferences']),
        'homeDashboardUID': value['homeDashboardUID'],
        'language': value['language'],
        'navbar': NavbarPreferenceToJSON(value['navbar']),
        'queryHistory': QueryHistoryPreferenceToJSON(value['queryHistory']),
        'theme': value['theme'],
        'timezone': value['timezone'],
        'weekStart': value['weekStart'],
    };
}

