/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RevokeAuthTokenCmd
 */
export interface RevokeAuthTokenCmd {
    /**
     * 
     * @type {number}
     * @memberof RevokeAuthTokenCmd
     */
    authTokenId?: number;
}

/**
 * Check if a given object implements the RevokeAuthTokenCmd interface.
 */
export function instanceOfRevokeAuthTokenCmd(value: object): value is RevokeAuthTokenCmd {
    return true;
}

export function RevokeAuthTokenCmdFromJSON(json: any): RevokeAuthTokenCmd {
    return RevokeAuthTokenCmdFromJSONTyped(json, false);
}

export function RevokeAuthTokenCmdFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeAuthTokenCmd {
    if (json == null) {
        return json;
    }
    return {
        
        'authTokenId': json['authTokenId'] == null ? undefined : json['authTokenId'],
    };
}

export function RevokeAuthTokenCmdToJSON(json: any): RevokeAuthTokenCmd {
    return RevokeAuthTokenCmdToJSONTyped(json, false);
}

export function RevokeAuthTokenCmdToJSONTyped(value?: RevokeAuthTokenCmd | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authTokenId': value['authTokenId'],
    };
}

