/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Label } from './Label';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label';

/**
 * adapted from cortex
 * @export
 * @interface Rule
 */
export interface Rule {
    /**
     * 
     * @type {number}
     * @memberof Rule
     */
    evaluationTime?: number;
    /**
     * 
     * @type {string}
     * @memberof Rule
     */
    health: string;
    /**
     * Labels is a sorted set of labels. Order has to be guaranteed upon
     * instantiation.
     * @type {Array<Label>}
     * @memberof Rule
     */
    labels?: Array<Label>;
    /**
     * 
     * @type {string}
     * @memberof Rule
     */
    lastError?: string;
    /**
     * 
     * @type {Date}
     * @memberof Rule
     */
    lastEvaluation?: Date;
    /**
     * 
     * @type {string}
     * @memberof Rule
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Rule
     */
    query: string;
    /**
     * 
     * @type {string}
     * @memberof Rule
     */
    type: string;
}

/**
 * Check if a given object implements the Rule interface.
 */
export function instanceOfRule(value: object): value is Rule {
    if (!('health' in value) || value['health'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RuleFromJSON(json: any): Rule {
    return RuleFromJSONTyped(json, false);
}

export function RuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rule {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationTime': json['evaluationTime'] == null ? undefined : json['evaluationTime'],
        'health': json['health'],
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(LabelFromJSON)),
        'lastError': json['lastError'] == null ? undefined : json['lastError'],
        'lastEvaluation': json['lastEvaluation'] == null ? undefined : (new Date(json['lastEvaluation'])),
        'name': json['name'],
        'query': json['query'],
        'type': json['type'],
    };
}

export function RuleToJSON(json: any): Rule {
    return RuleToJSONTyped(json, false);
}

export function RuleToJSONTyped(value?: Rule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluationTime': value['evaluationTime'],
        'health': value['health'],
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(LabelToJSON)),
        'lastError': value['lastError'],
        'lastEvaluation': value['lastEvaluation'] == null ? undefined : ((value['lastEvaluation']).toISOString()),
        'name': value['name'],
        'query': value['query'],
        'type': value['type'],
    };
}

