/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Label } from './Label';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label';

/**
 * 
 * @export
 * @interface Sample
 */
export interface Sample {
    /**
     * Labels is a sorted set of labels. Order has to be guaranteed upon
     * instantiation.
     * @type {Array<Label>}
     * @memberof Sample
     */
    metric?: Array<Label>;
    /**
     * 
     * @type {number}
     * @memberof Sample
     */
    t?: number;
    /**
     * 
     * @type {number}
     * @memberof Sample
     */
    v?: number;
}

/**
 * Check if a given object implements the Sample interface.
 */
export function instanceOfSample(value: object): value is Sample {
    return true;
}

export function SampleFromJSON(json: any): Sample {
    return SampleFromJSONTyped(json, false);
}

export function SampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sample {
    if (json == null) {
        return json;
    }
    return {
        
        'metric': json['Metric'] == null ? undefined : ((json['Metric'] as Array<any>).map(LabelFromJSON)),
        't': json['T'] == null ? undefined : json['T'],
        'v': json['V'] == null ? undefined : json['V'],
    };
}

export function SampleToJSON(json: any): Sample {
    return SampleToJSONTyped(json, false);
}

export function SampleToJSONTyped(value?: Sample | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Metric': value['metric'] == null ? undefined : ((value['metric'] as Array<any>).map(LabelToJSON)),
        'T': value['t'],
        'V': value['v'],
    };
}

