/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleDTO
 */
export interface ScheduleDTO {
    /**
     * 
     * @type {string}
     * @memberof ScheduleDTO
     */
    day?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleDTO
     */
    dayOfMonth?: string;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleDTO
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ScheduleDTO
     */
    frequency?: string;
    /**
     * 
     * @type {number}
     * @memberof ScheduleDTO
     */
    hour?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleDTO
     */
    intervalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduleDTO
     */
    intervalFrequency?: string;
    /**
     * 
     * @type {number}
     * @memberof ScheduleDTO
     */
    minute?: number;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleDTO
     */
    startDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ScheduleDTO
     */
    timeZone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduleDTO
     */
    workdaysOnly?: boolean;
}

/**
 * Check if a given object implements the ScheduleDTO interface.
 */
export function instanceOfScheduleDTO(value: object): value is ScheduleDTO {
    return true;
}

export function ScheduleDTOFromJSON(json: any): ScheduleDTO {
    return ScheduleDTOFromJSONTyped(json, false);
}

export function ScheduleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] == null ? undefined : json['day'],
        'dayOfMonth': json['dayOfMonth'] == null ? undefined : json['dayOfMonth'],
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'hour': json['hour'] == null ? undefined : json['hour'],
        'intervalAmount': json['intervalAmount'] == null ? undefined : json['intervalAmount'],
        'intervalFrequency': json['intervalFrequency'] == null ? undefined : json['intervalFrequency'],
        'minute': json['minute'] == null ? undefined : json['minute'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'timeZone': json['timeZone'] == null ? undefined : json['timeZone'],
        'workdaysOnly': json['workdaysOnly'] == null ? undefined : json['workdaysOnly'],
    };
}

export function ScheduleDTOToJSON(json: any): ScheduleDTO {
    return ScheduleDTOToJSONTyped(json, false);
}

export function ScheduleDTOToJSONTyped(value?: ScheduleDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'dayOfMonth': value['dayOfMonth'],
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'frequency': value['frequency'],
        'hour': value['hour'],
        'intervalAmount': value['intervalAmount'],
        'intervalFrequency': value['intervalFrequency'],
        'minute': value['minute'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'timeZone': value['timeZone'],
        'workdaysOnly': value['workdaysOnly'],
    };
}

