/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SnapshotDTO } from './SnapshotDTO.js';
import {
    SnapshotDTOFromJSON,
    SnapshotDTOFromJSONTyped,
    SnapshotDTOToJSON,
    SnapshotDTOToJSONTyped,
} from './SnapshotDTO.js';

/**
 * 
 * @export
 * @interface SnapshotListResponseDTO
 */
export interface SnapshotListResponseDTO {
    /**
     * 
     * @type {Array<SnapshotDTO>}
     * @memberof SnapshotListResponseDTO
     */
    snapshots?: Array<SnapshotDTO>;
}

/**
 * Check if a given object implements the SnapshotListResponseDTO interface.
 */
export function instanceOfSnapshotListResponseDTO(value: object): value is SnapshotListResponseDTO {
    return true;
}

export function SnapshotListResponseDTOFromJSON(json: any): SnapshotListResponseDTO {
    return SnapshotListResponseDTOFromJSONTyped(json, false);
}

export function SnapshotListResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotListResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshots': json['snapshots'] == null ? undefined : ((json['snapshots'] as Array<any>).map(SnapshotDTOFromJSON)),
    };
}

export function SnapshotListResponseDTOToJSON(json: any): SnapshotListResponseDTO {
    return SnapshotListResponseDTOToJSONTyped(json, false);
}

export function SnapshotListResponseDTOToJSONTyped(value?: SnapshotListResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snapshots': value['snapshots'] == null ? undefined : ((value['snapshots'] as Array<any>).map(SnapshotDTOToJSON)),
    };
}

