/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryHistoryPreference } from './QueryHistoryPreference';
import {
    QueryHistoryPreferenceFromJSON,
    QueryHistoryPreferenceFromJSONTyped,
    QueryHistoryPreferenceToJSON,
    QueryHistoryPreferenceToJSONTyped,
} from './QueryHistoryPreference';

/**
 * 
 * @export
 * @interface Spec
 */
export interface Spec {
    /**
     * UID for the home dashboard
     * @type {string}
     * @memberof Spec
     */
    homeDashboardUID?: string;
    /**
     * Selected language (beta)
     * @type {string}
     * @memberof Spec
     */
    language?: string;
    /**
     * 
     * @type {QueryHistoryPreference}
     * @memberof Spec
     */
    queryHistory?: QueryHistoryPreference;
    /**
     * Theme light, dark, empty is default
     * @type {string}
     * @memberof Spec
     */
    theme?: string;
    /**
     * The timezone selection
     * TODO: this should use the timezone defined in common
     * @type {string}
     * @memberof Spec
     */
    timezone?: string;
    /**
     * WeekStart day of the week (sunday, monday, etc)
     * @type {string}
     * @memberof Spec
     */
    weekStart?: string;
}

/**
 * Check if a given object implements the Spec interface.
 */
export function instanceOfSpec(value: object): value is Spec {
    return true;
}

export function SpecFromJSON(json: any): Spec {
    return SpecFromJSONTyped(json, false);
}

export function SpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): Spec {
    if (json == null) {
        return json;
    }
    return {
        
        'homeDashboardUID': json['homeDashboardUID'] == null ? undefined : json['homeDashboardUID'],
        'language': json['language'] == null ? undefined : json['language'],
        'queryHistory': json['queryHistory'] == null ? undefined : QueryHistoryPreferenceFromJSON(json['queryHistory']),
        'theme': json['theme'] == null ? undefined : json['theme'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'weekStart': json['weekStart'] == null ? undefined : json['weekStart'],
    };
}

export function SpecToJSON(json: any): Spec {
    return SpecToJSONTyped(json, false);
}

export function SpecToJSONTyped(value?: Spec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'homeDashboardUID': value['homeDashboardUID'],
        'language': value['language'],
        'queryHistory': QueryHistoryPreferenceToJSON(value['queryHistory']),
        'theme': value['theme'],
        'timezone': value['timezone'],
        'weekStart': value['weekStart'],
    };
}

