/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SSOSettings
 */
export interface SSOSettings {
    /**
     * 
     * @type {string}
     * @memberof SSOSettings
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SSOSettings
     */
    provider?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof SSOSettings
     */
    settings?: { [key: string]: object; };
    /**
     * 
     * @type {number}
     * @memberof SSOSettings
     */
    source?: number;
}

/**
 * Check if a given object implements the SSOSettings interface.
 */
export function instanceOfSSOSettings(value: object): value is SSOSettings {
    return true;
}

export function SSOSettingsFromJSON(json: any): SSOSettings {
    return SSOSettingsFromJSONTyped(json, false);
}

export function SSOSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SSOSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'settings': json['settings'] == null ? undefined : json['settings'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function SSOSettingsToJSON(json: any): SSOSettings {
    return SSOSettingsToJSONTyped(json, false);
}

export function SSOSettingsToJSONTyped(value?: SSOSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'provider': value['provider'],
        'settings': value['settings'],
        'source': value['source'],
    };
}

