/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TagsDTO
 */
export interface TagsDTO {
    /**
     * 
     * @type {number}
     * @memberof TagsDTO
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof TagsDTO
     */
    tag?: string;
}

/**
 * Check if a given object implements the TagsDTO interface.
 */
export function instanceOfTagsDTO(value: object): value is TagsDTO {
    return true;
}

export function TagsDTOFromJSON(json: any): TagsDTO {
    return TagsDTOFromJSONTyped(json, false);
}

export function TagsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function TagsDTOToJSON(json: any): TagsDTO {
    return TagsDTOToJSONTyped(json, false);
}

export function TagsDTOToJSONTyped(value?: TagsDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'tag': value['tag'],
    };
}

