/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestReceiverConfigResult } from './TestReceiverConfigResult';
import {
    TestReceiverConfigResultFromJSON,
    TestReceiverConfigResultFromJSONTyped,
    TestReceiverConfigResultToJSON,
    TestReceiverConfigResultToJSONTyped,
} from './TestReceiverConfigResult';

/**
 * 
 * @export
 * @interface TestReceiverResult
 */
export interface TestReceiverResult {
    /**
     * 
     * @type {Array<TestReceiverConfigResult>}
     * @memberof TestReceiverResult
     */
    grafanaManagedReceiverConfigs?: Array<TestReceiverConfigResult>;
    /**
     * 
     * @type {string}
     * @memberof TestReceiverResult
     */
    name?: string;
}

/**
 * Check if a given object implements the TestReceiverResult interface.
 */
export function instanceOfTestReceiverResult(value: object): value is TestReceiverResult {
    return true;
}

export function TestReceiverResultFromJSON(json: any): TestReceiverResult {
    return TestReceiverResultFromJSONTyped(json, false);
}

export function TestReceiverResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestReceiverResult {
    if (json == null) {
        return json;
    }
    return {
        
        'grafanaManagedReceiverConfigs': json['grafana_managed_receiver_configs'] == null ? undefined : ((json['grafana_managed_receiver_configs'] as Array<any>).map(TestReceiverConfigResultFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TestReceiverResultToJSON(json: any): TestReceiverResult {
    return TestReceiverResultToJSONTyped(json, false);
}

export function TestReceiverResultToJSONTyped(value?: TestReceiverResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grafana_managed_receiver_configs': value['grafanaManagedReceiverConfigs'] == null ? undefined : ((value['grafanaManagedReceiverConfigs'] as Array<any>).map(TestReceiverConfigResultToJSON)),
        'name': value['name'],
    };
}

