/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TimeIntervalTimeRange
 */
export interface TimeIntervalTimeRange {
    /**
     * 
     * @type {string}
     * @memberof TimeIntervalTimeRange
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeIntervalTimeRange
     */
    startTime?: string;
}

/**
 * Check if a given object implements the TimeIntervalTimeRange interface.
 */
export function instanceOfTimeIntervalTimeRange(value: object): value is TimeIntervalTimeRange {
    return true;
}

export function TimeIntervalTimeRangeFromJSON(json: any): TimeIntervalTimeRange {
    return TimeIntervalTimeRangeFromJSONTyped(json, false);
}

export function TimeIntervalTimeRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeIntervalTimeRange {
    if (json == null) {
        return json;
    }
    return {
        
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
    };
}

export function TimeIntervalTimeRangeToJSON(json: any): TimeIntervalTimeRange {
    return TimeIntervalTimeRangeToJSONTyped(json, false);
}

export function TimeIntervalTimeRangeToJSONTyped(value?: TimeIntervalTimeRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_time': value['endTime'],
        'start_time': value['startTime'],
    };
}

