/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeRange } from './TimeRange';
import {
    TimeRangeFromJSON,
    TimeRangeFromJSONTyped,
    TimeRangeToJSON,
    TimeRangeToJSONTyped,
} from './TimeRange';

/**
 * TimeInterval describes intervals of time. ContainsTime will tell you if a golang time is contained
 * within the interval.
 * @export
 * @interface TimeInterval
 */
export interface TimeInterval {
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeInterval
     */
    daysOfMonth?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TimeInterval
     */
    location?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeInterval
     */
    months?: Array<string>;
    /**
     * 
     * @type {Array<TimeRange>}
     * @memberof TimeInterval
     */
    times?: Array<TimeRange>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeInterval
     */
    weekdays?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeInterval
     */
    years?: Array<string>;
}

/**
 * Check if a given object implements the TimeInterval interface.
 */
export function instanceOfTimeInterval(value: object): value is TimeInterval {
    return true;
}

export function TimeIntervalFromJSON(json: any): TimeInterval {
    return TimeIntervalFromJSONTyped(json, false);
}

export function TimeIntervalFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeInterval {
    if (json == null) {
        return json;
    }
    return {
        
        'daysOfMonth': json['days_of_month'] == null ? undefined : json['days_of_month'],
        'location': json['location'] == null ? undefined : json['location'],
        'months': json['months'] == null ? undefined : json['months'],
        'times': json['times'] == null ? undefined : ((json['times'] as Array<any>).map(TimeRangeFromJSON)),
        'weekdays': json['weekdays'] == null ? undefined : json['weekdays'],
        'years': json['years'] == null ? undefined : json['years'],
    };
}

export function TimeIntervalToJSON(json: any): TimeInterval {
    return TimeIntervalToJSONTyped(json, false);
}

export function TimeIntervalToJSONTyped(value?: TimeInterval | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'days_of_month': value['daysOfMonth'],
        'location': value['location'],
        'months': value['months'],
        'times': value['times'] == null ? undefined : ((value['times'] as Array<any>).map(TimeRangeToJSON)),
        'weekdays': value['weekdays'],
        'years': value['years'],
    };
}

