/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateOrgUserCommand
 */
export interface UpdateOrgUserCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateOrgUserCommand
     */
    role?: UpdateOrgUserCommandRoleEnum;
}


/**
 * @export
 */
export const UpdateOrgUserCommandRoleEnum = {
    None: 'None',
    Viewer: 'Viewer',
    Editor: 'Editor',
    Admin: 'Admin'
} as const;
export type UpdateOrgUserCommandRoleEnum = typeof UpdateOrgUserCommandRoleEnum[keyof typeof UpdateOrgUserCommandRoleEnum];


/**
 * Check if a given object implements the UpdateOrgUserCommand interface.
 */
export function instanceOfUpdateOrgUserCommand(value: object): value is UpdateOrgUserCommand {
    return true;
}

export function UpdateOrgUserCommandFromJSON(json: any): UpdateOrgUserCommand {
    return UpdateOrgUserCommandFromJSONTyped(json, false);
}

export function UpdateOrgUserCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrgUserCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function UpdateOrgUserCommandToJSON(json: any): UpdateOrgUserCommand {
    return UpdateOrgUserCommandToJSONTyped(json, false);
}

export function UpdateOrgUserCommandToJSONTyped(value?: UpdateOrgUserCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

