/* tslint:disable */
/* eslint-disable */
/**
 * Grafana HTTP API.
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: hello@grafana.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeamLBACRule } from './TeamLBACRule';
import {
    TeamLBACRuleFromJSON,
    TeamLBACRuleFromJSONTyped,
    TeamLBACRuleToJSON,
    TeamLBACRuleToJSONTyped,
} from './TeamLBACRule';

/**
 * 
 * @export
 * @interface UpdateTeamLBACCommand
 */
export interface UpdateTeamLBACCommand {
    /**
     * 
     * @type {Array<TeamLBACRule>}
     * @memberof UpdateTeamLBACCommand
     */
    rules?: Array<TeamLBACRule>;
}

/**
 * Check if a given object implements the UpdateTeamLBACCommand interface.
 */
export function instanceOfUpdateTeamLBACCommand(value: object): value is UpdateTeamLBACCommand {
    return true;
}

export function UpdateTeamLBACCommandFromJSON(json: any): UpdateTeamLBACCommand {
    return UpdateTeamLBACCommandFromJSONTyped(json, false);
}

export function UpdateTeamLBACCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTeamLBACCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'rules': json['rules'] == null ? undefined : ((json['rules'] as Array<any>).map(TeamLBACRuleFromJSON)),
    };
}

export function UpdateTeamLBACCommandToJSON(json: any): UpdateTeamLBACCommand {
    return UpdateTeamLBACCommandToJSONTyped(json, false);
}

export function UpdateTeamLBACCommandToJSONTyped(value?: UpdateTeamLBACCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rules': value['rules'] == null ? undefined : ((value['rules'] as Array<any>).map(TeamLBACRuleToJSON)),
    };
}

